{% set name = "pyometiff" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyometiff-{{ version }}.tar.gz
  sha256: 596b7a7377a5f2e50292aa52dd22e6347a2d2f21577e93d1fcdcd63942e597f7
  patches:
    - require.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - lxml
    - tifffile >2020.10.1
    - numpy
    - imagecodecs

test:
  imports:
    - pyometiff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/filippocastelli/pyometiff
  summary: Read and Write OME-TIFFs in Python
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
